import type { Recipe } from "../artwork/types";

export const RECIPES: Recipe[] = [
  // ─── LIVING FIELDS ──────────────────────────────────────────────────────
  {
    id: "lf-nebula",
    family: "living-fields",
    name: "Nebula",
    tagline: "Deep, slow, luminous cosmic clouds.",
    changes: [
      { system: "form", path: "form.density", value: 1.6 },
      { system: "form", path: "form.warp", value: 1.4 },
      { system: "form", path: "form.detail", value: 5 },
      { system: "motion", path: "motion.speed", value: 0.12 },
      { system: "motion", path: "motion.turbulence", value: 0.4 },
      { system: "color", path: "color.hue", value: 0.72 },
      { system: "color", path: "color.spread", value: 0.55 },
      { system: "light", path: "light.bloom", value: 0.8 },
    ],
  },
  {
    id: "lf-magma",
    family: "living-fields",
    name: "Magma",
    tagline: "Hot, viscous, restless flow.",
    changes: [
      { system: "form", path: "form.density", value: 3.4 },
      { system: "form", path: "form.warp", value: 0.6 },
      { system: "motion", path: "motion.speed", value: 0.55 },
      { system: "motion", path: "motion.turbulence", value: 1.2 },
      { system: "color", path: "color.hue", value: 0.05 },
      { system: "color", path: "color.spread", value: 0.3 },
      { system: "color", path: "color.contrast", value: 1.4 },
      { system: "light", path: "light.bloom", value: 0.7 },
    ],
  },
  {
    id: "lf-aurora",
    family: "living-fields",
    name: "Aurora",
    tagline: "Slow curtains of green and violet light.",
    changes: [
      { system: "form", path: "form.density", value: 1.2 },
      { system: "form", path: "form.warp", value: 1.7 },
      { system: "form", path: "form.detail", value: 3 },
      { system: "motion", path: "motion.speed", value: 0.08 },
      { system: "motion", path: "motion.turbulence", value: 0.25 },
      { system: "motion", path: "motion.drift", value: 0.35 },
      { system: "color", path: "color.hue", value: 0.42 },
      { system: "color", path: "color.spread", value: 0.7 },
      { system: "color", path: "color.luminosity", value: 1.15 },
      { system: "light", path: "light.bloom", value: 0.85 },
    ],
  },
  {
    id: "lf-tide",
    family: "living-fields",
    name: "Tide",
    tagline: "Rolling swells of blue-green matter.",
    changes: [
      { system: "form", path: "form.density", value: 2.4 },
      { system: "form", path: "form.warp", value: 1.1 },
      { system: "motion", path: "motion.speed", value: 0.28 },
      { system: "motion", path: "motion.turbulence", value: 0.75 },
      { system: "motion", path: "motion.drift", value: -0.25 },
      { system: "color", path: "color.hue", value: 0.52 },
      { system: "color", path: "color.spread", value: 0.32 },
      { system: "color", path: "color.contrast", value: 1.1 },
    ],
  },
  {
    id: "lf-static",
    family: "living-fields",
    name: "Static",
    tagline: "High-frequency shimmer, cold and dense.",
    changes: [
      { system: "form", path: "form.density", value: 5.2 },
      { system: "form", path: "form.detail", value: 6 },
      { system: "form", path: "form.warp", value: 0.35 },
      { system: "motion", path: "motion.speed", value: 0.7 },
      { system: "motion", path: "motion.turbulence", value: 1.5 },
      { system: "color", path: "color.hue", value: 0.62 },
      { system: "color", path: "color.spread", value: 0.15 },
      { system: "color", path: "color.contrast", value: 1.6 },
      { system: "light", path: "light.grain", value: 0.14 },
    ],
  },
  {
    id: "lf-breath",
    family: "living-fields",
    name: "Breath",
    tagline: "Almost still — a single body inhaling.",
    changes: [
      { system: "form", path: "form.density", value: 0.9 },
      { system: "form", path: "form.warp", value: 0.9 },
      { system: "form", path: "form.detail", value: 2 },
      { system: "motion", path: "motion.speed", value: 0.06 },
      { system: "motion", path: "motion.turbulence", value: 0.15 },
      { system: "color", path: "color.hue", value: 0.09 },
      { system: "color", path: "color.spread", value: 0.2 },
      { system: "color", path: "color.luminosity", value: 1.05 },
      { system: "light", path: "light.bloom", value: 0.65 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "lf-ember",
    family: "living-fields",
    name: "Ember",
    tagline: "Dark field with glowing coal veins.",
    changes: [
      { system: "form", path: "form.density", value: 2.6 },
      { system: "form", path: "form.warp", value: 1.2 },
      { system: "motion", path: "motion.speed", value: 0.2 },
      { system: "motion", path: "motion.turbulence", value: 0.9 },
      { system: "color", path: "color.hue", value: 0.02 },
      { system: "color", path: "color.spread", value: 0.45 },
      { system: "color", path: "color.contrast", value: 1.55 },
      { system: "color", path: "color.luminosity", value: 0.75 },
      { system: "light", path: "light.bloom", value: 0.7 },
      { system: "output", path: "output.vignette", value: 0.6 },
    ],
  },
  {
    id: "lf-glass-sea",
    family: "living-fields",
    name: "Glass Sea",
    tagline: "Cold, still, refractive.",
    changes: [
      { system: "form", path: "form.density", value: 1.4 },
      { system: "form", path: "form.warp", value: 0.4 },
      { system: "motion", path: "motion.speed", value: 0.15 },
      { system: "motion", path: "motion.turbulence", value: 0.35 },
      { system: "color", path: "color.hue", value: 0.58 },
      { system: "color", path: "color.spread", value: 0.22 },
      { system: "color", path: "color.luminosity", value: 1.2 },
      { system: "light", path: "light.bloom", value: 0.5 },
    ],
  },
  // ─── MATERIAL FORMS ─────────────────────────────────────────────────────
  {
    id: "mf-chrome",
    family: "material-forms",
    name: "Chrome",
    tagline: "Polished metallic sculpture.",
    changes: [
      { system: "material", path: "material.metalness", value: 1 },
      { system: "material", path: "material.roughness", value: 0.1 },
      { system: "form", path: "form.size", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.6 },
    ],
  },
  {
    id: "mf-clay",
    family: "material-forms",
    name: "Wet Clay",
    tagline: "Soft matte body.",
    changes: [
      { system: "material", path: "material.metalness", value: 0 },
      { system: "material", path: "material.roughness", value: 0.9 },
      { system: "form", path: "form.size", value: 0.7 },
      { system: "color", path: "color.hue", value: 0.08 },
    ],
  },
  {
    id: "mf-pearl",
    family: "material-forms",
    name: "Pearl",
    tagline: "Iridescent luminous body.",
    changes: [
      { system: "material", path: "material.metalness", value: 0.15 },
      { system: "material", path: "material.roughness", value: 0.25 },
      { system: "material", path: "material.iridescence", value: 0.95 },
      { system: "form", path: "form.size", value: 0.62 },
      { system: "form", path: "form.smoothness", value: 0.28 },
      { system: "color", path: "color.hue", value: 0.86 },
      { system: "color", path: "color.saturation", value: 0.35 },
      { system: "light", path: "light.intensity", value: 1.25 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.18 },
    ],
  },
  {
    id: "mf-obsidian",
    family: "material-forms",
    name: "Obsidian",
    tagline: "Sharp, dark, glassy volcanic mass.",
    changes: [
      { system: "material", path: "material.metalness", value: 0.05 },
      { system: "material", path: "material.roughness", value: 0.05 },
      { system: "material", path: "material.iridescence", value: 0.1 },
      { system: "form", path: "form.size", value: 0.5 },
      { system: "form", path: "form.smoothness", value: 0.06 },
      { system: "form", path: "form.cluster", value: 4 },
      { system: "color", path: "color.hue", value: 0.72 },
      { system: "color", path: "color.saturation", value: 0.15 },
      { system: "light", path: "light.intensity", value: 0.85 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "mf-wax",
    family: "material-forms",
    name: "Wax",
    tagline: "Warm translucent softness.",
    changes: [
      { system: "material", path: "material.metalness", value: 0 },
      { system: "material", path: "material.roughness", value: 0.55 },
      { system: "material", path: "material.iridescence", value: 0.1 },
      { system: "form", path: "form.size", value: 0.72 },
      { system: "form", path: "form.smoothness", value: 0.34 },
      { system: "color", path: "color.hue", value: 0.11 },
      { system: "color", path: "color.saturation", value: 0.5 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.4 },
    ],
  },
  {
    id: "mf-bronze",
    family: "material-forms",
    name: "Bronze",
    tagline: "Ancient patinated metal.",
    changes: [
      { system: "material", path: "material.metalness", value: 0.85 },
      { system: "material", path: "material.roughness", value: 0.45 },
      { system: "material", path: "material.iridescence", value: 0.05 },
      { system: "form", path: "form.size", value: 0.6 },
      { system: "color", path: "color.hue", value: 0.09 },
      { system: "color", path: "color.saturation", value: 0.65 },
      { system: "light", path: "light.intensity", value: 1.05 },
    ],
  },
  {
    id: "mf-mercury",
    family: "material-forms",
    name: "Mercury",
    tagline: "Liquid metal beading and merging.",
    changes: [
      { system: "material", path: "material.metalness", value: 1 },
      { system: "material", path: "material.roughness", value: 0.02 },
      { system: "material", path: "material.iridescence", value: 0.3 },
      { system: "form", path: "form.size", value: 0.45 },
      { system: "form", path: "form.smoothness", value: 0.45 },
      { system: "form", path: "form.cluster", value: 5 },
      { system: "color", path: "color.hue", value: 0.62 },
      { system: "color", path: "color.saturation", value: 0.2 },
    ],
  },
  // ─── TEMPORAL PAINTINGS ─────────────────────────────────────────────────
  {
    id: "tp-watercolor",
    family: "temporal-paintings",
    name: "Watercolour",
    tagline: "Bleeding pigment on wet paper.",
    changes: [
      { system: "memory", path: "memory.persistence", value: 0.9 },
      { system: "form", path: "form.brush", value: 0.7 },
      { system: "motion", path: "motion.flow", value: 0.3 },
      { system: "color", path: "color.hue", value: 0.55 },
    ],
  },
  {
    id: "tp-ink-storm",
    family: "temporal-paintings",
    name: "Ink Storm",
    tagline: "Violent black ink whipping across paper.",
    changes: [
      { system: "form", path: "form.brush", value: 1.2 },
      { system: "form", path: "form.strokes", value: 5 },
      { system: "motion", path: "motion.flow", value: 1.2 },
      { system: "motion", path: "motion.chaos", value: 0.85 },
      { system: "memory", path: "memory.persistence", value: 0.55 },
      { system: "memory", path: "memory.bleed", value: 0.65 },
      { system: "memory", path: "memory.feedback", value: 0.85 },
      { system: "color", path: "color.hue", value: 0.66 },
      { system: "color", path: "color.spread", value: 0.1 },
      { system: "color", path: "color.contrast", value: 1.6 },
    ],
  },
  {
    id: "tp-fresco",
    family: "temporal-paintings",
    name: "Fresco",
    tagline: "Slow chalky pigment settling on plaster.",
    changes: [
      { system: "form", path: "form.brush", value: 0.5 },
      { system: "form", path: "form.strokes", value: 2 },
      { system: "motion", path: "motion.flow", value: 0.2 },
      { system: "motion", path: "motion.chaos", value: 0.15 },
      { system: "memory", path: "memory.persistence", value: 0.96 },
      { system: "memory", path: "memory.bleed", value: 0.15 },
      { system: "color", path: "color.hue", value: 0.08 },
      { system: "color", path: "color.spread", value: 0.55 },
      { system: "color", path: "color.contrast", value: 0.9 },
    ],
  },
  {
    id: "tp-oil",
    family: "temporal-paintings",
    name: "Oil",
    tagline: "Thick impasto smearing slowly.",
    changes: [
      { system: "form", path: "form.brush", value: 1.4 },
      { system: "form", path: "form.strokes", value: 4 },
      { system: "motion", path: "motion.flow", value: 0.45 },
      { system: "motion", path: "motion.chaos", value: 0.3 },
      { system: "memory", path: "memory.persistence", value: 0.88 },
      { system: "memory", path: "memory.bleed", value: 0.28 },
      { system: "color", path: "color.hue", value: 0.04 },
      { system: "color", path: "color.spread", value: 0.7 },
      { system: "color", path: "color.contrast", value: 1.25 },
    ],
  },
  {
    id: "tp-neon-trail",
    family: "temporal-paintings",
    name: "Neon Trail",
    tagline: "Long luminous trails on black.",
    changes: [
      { system: "form", path: "form.brush", value: 0.35 },
      { system: "form", path: "form.strokes", value: 3 },
      { system: "motion", path: "motion.flow", value: 0.9 },
      { system: "motion", path: "motion.chaos", value: 0.55 },
      { system: "memory", path: "memory.persistence", value: 0.94 },
      { system: "memory", path: "memory.bleed", value: 0.35 },
      { system: "memory", path: "memory.feedback", value: 1 },
      { system: "color", path: "color.hue", value: 0.83 },
      { system: "color", path: "color.spread", value: 0.65 },
      { system: "color", path: "color.contrast", value: 1.7 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "tp-dust",
    family: "temporal-paintings",
    name: "Dust",
    tagline: "Barely-there particulate drift.",
    changes: [
      { system: "form", path: "form.brush", value: 0.2 },
      { system: "form", path: "form.strokes", value: 6 },
      { system: "motion", path: "motion.flow", value: 0.3 },
      { system: "motion", path: "motion.chaos", value: 0.7 },
      { system: "memory", path: "memory.persistence", value: 0.82 },
      { system: "memory", path: "memory.bleed", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.1 },
      { system: "color", path: "color.spread", value: 0.4 },
      { system: "color", path: "color.contrast", value: 0.75 },
    ],
  },
  // ─── TYPOGRAPHIC ORGANISMS ──────────────────────────────────────────────
  {
    id: "to-glyph-choir",
    family: "typographic-organisms",
    name: "Glyph Choir",
    tagline: "Marching letters in unison.",
    changes: [
      { system: "form", path: "form.cellSize", value: 22 },
      { system: "form", path: "form.weight", value: 0.6 },
      { system: "motion", path: "motion.speed", value: 0.5 },
      { system: "color", path: "color.hue", value: 0.15 },
    ],
  },
  {
    id: "to-signal-rain",
    family: "typographic-organisms",
    name: "Signal Rain",
    tagline: "Dense terminal characters cascading.",
    changes: [
      { system: "form", path: "form.cellSize", value: 14 },
      { system: "form", path: "form.weight", value: 0.75 },
      { system: "form", path: "form.jitter", value: 0.15 },
      { system: "motion", path: "motion.speed", value: 0.9 },
      { system: "motion", path: "motion.breath", value: 0.1 },
      { system: "material", path: "material.softness", value: 0.008 },
      { system: "color", path: "color.hue", value: 0.36 },
      { system: "color", path: "color.contrast", value: 1.6 },
    ],
  },
  {
    id: "to-broadside",
    family: "typographic-organisms",
    name: "Broadside",
    tagline: "Bold newspaper poster grid.",
    changes: [
      { system: "form", path: "form.cellSize", value: 56 },
      { system: "form", path: "form.weight", value: 0.9 },
      { system: "form", path: "form.jitter", value: 0.05 },
      { system: "motion", path: "motion.speed", value: 0.15 },
      { system: "motion", path: "motion.breath", value: 0.7 },
      { system: "material", path: "material.softness", value: 0.01 },
      { system: "color", path: "color.hue", value: 0 },
      { system: "color", path: "color.contrast", value: 1.7 },
    ],
  },
  {
    id: "to-hymn",
    family: "typographic-organisms",
    name: "Hymn",
    tagline: "Soft-focus glyphs breathing gently.",
    changes: [
      { system: "form", path: "form.cellSize", value: 40 },
      { system: "form", path: "form.weight", value: 0.4 },
      { system: "form", path: "form.jitter", value: 0.45 },
      { system: "motion", path: "motion.speed", value: 0.2 },
      { system: "motion", path: "motion.breath", value: 0.85 },
      { system: "material", path: "material.softness", value: 0.12 },
      { system: "color", path: "color.hue", value: 0.78 },
      { system: "color", path: "color.contrast", value: 0.85 },
      { system: "output", path: "output.vignette", value: 0.5 },
    ],
  },
  {
    id: "to-swarm",
    family: "typographic-organisms",
    name: "Swarm",
    tagline: "Chaotic scattering of tiny characters.",
    changes: [
      { system: "form", path: "form.cellSize", value: 18 },
      { system: "form", path: "form.weight", value: 0.5 },
      { system: "form", path: "form.jitter", value: 0.85 },
      { system: "motion", path: "motion.speed", value: 1.2 },
      { system: "motion", path: "motion.breath", value: 0.35 },
      { system: "material", path: "material.softness", value: 0.03 },
      { system: "color", path: "color.hue", value: 0.55 },
      { system: "color", path: "color.contrast", value: 1.3 },
    ],
  },
  // ─── SPATIAL ILLUSIONS ──────────────────────────────────────────────────
  {
    id: "si-portal",
    family: "spatial-illusions",
    name: "Portal",
    tagline: "Deep tunnel with warped light.",
    changes: [
      { system: "form", path: "form.depth", value: 1.6 },
      { system: "form", path: "form.twist", value: 0.9 },
      { system: "motion", path: "motion.speed", value: 0.4 },
      { system: "color", path: "color.hue", value: 0.78 },
    ],
  },
  {
    id: "si-vortex",
    family: "spatial-illusions",
    name: "Vortex",
    tagline: "Fast spiralling implosion.",
    changes: [
      { system: "form", path: "form.depth", value: 2.4 },
      { system: "form", path: "form.twist", value: 1.4 },
      { system: "form", path: "form.rings", value: 18 },
      { system: "motion", path: "motion.speed", value: 1.1 },
      { system: "motion", path: "motion.warble", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.02 },
      { system: "color", path: "color.contrast", value: 1.5 },
      { system: "light", path: "light.bloom", value: 0.8 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.65 },
    ],
  },
  {
    id: "si-cathedral",
    family: "spatial-illusions",
    name: "Cathedral",
    tagline: "Slow vaulted architectural depth.",
    changes: [
      { system: "form", path: "form.depth", value: 2.8 },
      { system: "form", path: "form.twist", value: -0.4 },
      { system: "form", path: "form.rings", value: 8 },
      { system: "motion", path: "motion.speed", value: 0.1 },
      { system: "motion", path: "motion.warble", value: 0.08 },
      { system: "color", path: "color.hue", value: 0.13 },
      { system: "color", path: "color.contrast", value: 1.35 },
      { system: "light", path: "light.bloom", value: 0.9 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.8 },
      { system: "output", path: "output.vignette", value: 0.7 },
    ],
  },
  {
    id: "si-moire",
    family: "spatial-illusions",
    name: "Moiré",
    tagline: "Interference-pattern shimmer.",
    changes: [
      { system: "form", path: "form.depth", value: 0.6 },
      { system: "form", path: "form.twist", value: 0.15 },
      { system: "form", path: "form.rings", value: 24 },
      { system: "motion", path: "motion.speed", value: 0.55 },
      { system: "motion", path: "motion.warble", value: 0.8 },
      { system: "color", path: "color.hue", value: 0.5 },
      { system: "color", path: "color.contrast", value: 1.55 },
      { system: "light", path: "light.bloom", value: 0.3 },
    ],
  },
  {
    id: "si-mobius",
    family: "spatial-illusions",
    name: "Möbius",
    tagline: "Impossible ribbon folding on itself.",
    changes: [
      { system: "form", path: "form.depth", value: 1.8 },
      { system: "form", path: "form.twist", value: -1.2 },
      { system: "form", path: "form.rings", value: 14 },
      { system: "motion", path: "motion.speed", value: 0.25 },
      { system: "motion", path: "motion.warble", value: 0.35 },
      { system: "color", path: "color.hue", value: 0.88 },
      { system: "color", path: "color.contrast", value: 1.25 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.35 },
    ],
  },
  {
    id: "si-abyss",
    family: "spatial-illusions",
    name: "Abyss",
    tagline: "Bottomless dark descending well.",
    changes: [
      { system: "form", path: "form.depth", value: 2.9 },
      { system: "form", path: "form.twist", value: 0.25 },
      { system: "form", path: "form.rings", value: 6 },
      { system: "motion", path: "motion.speed", value: 0.35 },
      { system: "motion", path: "motion.warble", value: 0.15 },
      { system: "color", path: "color.hue", value: 0.6 },
      { system: "color", path: "color.contrast", value: 1.7 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.9 },
      { system: "output", path: "output.vignette", value: 0.8 },
    ],
  },
];

export function recipesForFamily(family: string): Recipe[] {
  return RECIPES.filter((r) => r.family === family);
}
