import type { Recipe } from "../artwork/types";

export const RECIPES: Recipe[] = [
  // ─── LIVING FIELDS ──────────────────────────────────────────────────────
  {
    id: "lf-nebula",
    family: "living-fields",
    name: "Nebula",
    tagline: "Deep, slow, luminous cosmic clouds.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.density", value: 1.4 },
      { system: "form", path: "form.warp", value: 1.6 },
      { system: "form", path: "form.detail", value: 5 },
      { system: "form", path: "form.structure", value: 0.65 },
      { system: "motion", path: "motion.speed", value: 0.28 },
      { system: "motion", path: "motion.turbulence", value: 0.55 },
      { system: "motion", path: "motion.drift", value: 0.12 },
      { system: "color", path: "color.hue", value: 0.74 },
      { system: "color", path: "color.spread", value: 0.95 },
      { system: "color", path: "color.contrast", value: 1.2 },
      { system: "color", path: "color.luminosity", value: 1.05 },
      { system: "light", path: "light.bloom", value: 0.85 },
      { system: "output", path: "output.vignette", value: 0.5 },
    ],
  },
  {
    id: "lf-magma",
    family: "living-fields",
    name: "Magma",
    tagline: "Hot, viscous, restless flow.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.density", value: 2.0 },
      { system: "form", path: "form.detail", value: 5 },
      { system: "form", path: "form.warp", value: 1.3 },
      { system: "form", path: "form.structure", value: 0.55 },
      { system: "motion", path: "motion.speed", value: 0.55 },
      { system: "motion", path: "motion.turbulence", value: 0.9 },
      { system: "motion", path: "motion.drift", value: 0.2 },
      { system: "color", path: "color.hue", value: 0.03 },
      { system: "color", path: "color.spread", value: 0.55 },
      { system: "color", path: "color.contrast", value: 1.45 },
      { system: "color", path: "color.luminosity", value: 1.0 },
      { system: "light", path: "light.bloom", value: 0.8 },
      { system: "light", path: "light.grain", value: 0.008 },
    ],
  },
  {
    id: "lf-aurora",
    family: "living-fields",
    name: "Aurora",
    tagline: "Slow curtains of green and violet light.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.density", value: 1.6 },
      { system: "form", path: "form.warp", value: 1.8 },
      { system: "form", path: "form.detail", value: 4 },
      { system: "form", path: "form.structure", value: 0.85 },
      { system: "motion", path: "motion.speed", value: 0.3 },
      { system: "motion", path: "motion.turbulence", value: 0.4 },
      { system: "motion", path: "motion.drift", value: 0.5 },
      { system: "color", path: "color.hue", value: 0.42 },
      { system: "color", path: "color.spread", value: 0.85 },
      { system: "color", path: "color.contrast", value: 1.15 },
      { system: "color", path: "color.luminosity", value: 1.15 },
      { system: "light", path: "light.bloom", value: 0.9 },
      { system: "output", path: "output.vignette", value: 0.35 },
    ],
  },
  {
    id: "lf-tide",
    family: "living-fields",
    name: "Tide",
    tagline: "Rolling swells of blue-green matter.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.density", value: 1.9 },
      { system: "form", path: "form.warp", value: 1.3 },
      { system: "form", path: "form.structure", value: 0.7 },
      { system: "motion", path: "motion.speed", value: 0.4 },
      { system: "motion", path: "motion.turbulence", value: 0.9 },
      { system: "motion", path: "motion.drift", value: -0.4 },
      { system: "color", path: "color.hue", value: 0.5 },
      { system: "color", path: "color.spread", value: 0.6 },
      { system: "color", path: "color.contrast", value: 1.2 },
      { system: "color", path: "color.luminosity", value: 1.0 },
      { system: "light", path: "light.bloom", value: 0.55 },
    ],
  },
  {
    id: "lf-static",
    family: "living-fields",
    name: "Static",
    tagline: "Crackling reaction lattice.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.density", value: 2.4 },
      { system: "form", path: "form.detail", value: 4 },
      { system: "form", path: "form.warp", value: 0.6 },
      { system: "form", path: "form.structure", value: 0.3 },
      { system: "motion", path: "motion.speed", value: 0.75 },
      { system: "motion", path: "motion.turbulence", value: 1.1 },
      { system: "color", path: "color.hue", value: 0.62 },
      { system: "color", path: "color.spread", value: 0.7 },
      { system: "color", path: "color.contrast", value: 1.5 },
      { system: "color", path: "color.luminosity", value: 1.1 },
      { system: "light", path: "light.bloom", value: 0.5 },
      { system: "light", path: "light.grain", value: 0.015 },
    ],
  },
  {
    id: "lf-breath",
    family: "living-fields",
    name: "Breath",
    tagline: "Almost still — a single body inhaling.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.density", value: 0.9 },
      { system: "form", path: "form.warp", value: 1.2 },
      { system: "form", path: "form.detail", value: 3 },
      { system: "form", path: "form.structure", value: 0.9 },
      { system: "motion", path: "motion.speed", value: 0.18 },
      { system: "motion", path: "motion.turbulence", value: 0.25 },
      { system: "color", path: "color.hue", value: 0.06 },
      { system: "color", path: "color.spread", value: 0.5 },
      { system: "color", path: "color.contrast", value: 1.1 },
      { system: "color", path: "color.luminosity", value: 1.15 },
      { system: "light", path: "light.bloom", value: 0.75 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "lf-ember",
    family: "living-fields",
    name: "Ember",
    tagline: "Dark field with glowing coal veins.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.density", value: 2.4 },
      { system: "form", path: "form.warp", value: 1.5 },
      { system: "form", path: "form.structure", value: 0.5 },
      { system: "motion", path: "motion.speed", value: 0.35 },
      { system: "motion", path: "motion.turbulence", value: 1.0 },
      { system: "color", path: "color.hue", value: 0.02 },
      { system: "color", path: "color.spread", value: 0.75 },
      { system: "color", path: "color.contrast", value: 1.7 },
      { system: "color", path: "color.luminosity", value: 0.8 },
      { system: "light", path: "light.bloom", value: 0.85 },
      { system: "output", path: "output.vignette", value: 0.65 },
    ],
  },
  {
    id: "lf-glass-sea",
    family: "living-fields",
    name: "Glass Sea",
    tagline: "Refractive cold currents.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.density", value: 1.7 },
      { system: "form", path: "form.warp", value: 0.7 },
      { system: "form", path: "form.structure", value: 0.75 },
      { system: "motion", path: "motion.speed", value: 0.35 },
      { system: "motion", path: "motion.turbulence", value: 0.6 },
      { system: "motion", path: "motion.drift", value: 0.25 },
      { system: "color", path: "color.hue", value: 0.56 },
      { system: "color", path: "color.spread", value: 0.8 },
      { system: "color", path: "color.contrast", value: 1.3 },
      { system: "color", path: "color.luminosity", value: 1.15 },
      { system: "light", path: "light.bloom", value: 0.6 },
    ],
  },
  // ─── MATERIAL FORMS ─────────────────────────────────────────────────────
  {
    id: "mf-chrome",
    family: "material-forms",
    name: "Chrome",
    tagline: "Polished metallic sculpture.",
    changes: [
      { system: "material", path: "material.metalness", value: 1 },
      { system: "material", path: "material.roughness", value: 0.1 },
      { system: "form", path: "form.size", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.6 },
    ],
  },
  {
    id: "mf-clay",
    family: "material-forms",
    name: "Wet Clay",
    tagline: "Soft matte body.",
    changes: [
      { system: "material", path: "material.metalness", value: 0 },
      { system: "material", path: "material.roughness", value: 0.9 },
      { system: "form", path: "form.size", value: 0.7 },
      { system: "color", path: "color.hue", value: 0.08 },
    ],
  },
  {
    id: "mf-pearl",
    family: "material-forms",
    name: "Pearl",
    tagline: "Iridescent luminous body.",
    changes: [
      { system: "material", path: "material.metalness", value: 0.15 },
      { system: "material", path: "material.roughness", value: 0.25 },
      { system: "material", path: "material.iridescence", value: 0.95 },
      { system: "form", path: "form.size", value: 0.62 },
      { system: "form", path: "form.smoothness", value: 0.28 },
      { system: "color", path: "color.hue", value: 0.86 },
      { system: "color", path: "color.saturation", value: 0.35 },
      { system: "light", path: "light.intensity", value: 1.25 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.18 },
    ],
  },
  {
    id: "mf-obsidian",
    family: "material-forms",
    name: "Obsidian",
    tagline: "Sharp, dark, glassy volcanic mass.",
    changes: [
      { system: "material", path: "material.metalness", value: 0.05 },
      { system: "material", path: "material.roughness", value: 0.05 },
      { system: "material", path: "material.iridescence", value: 0.1 },
      { system: "form", path: "form.size", value: 0.5 },
      { system: "form", path: "form.smoothness", value: 0.06 },
      { system: "form", path: "form.cluster", value: 4 },
      { system: "color", path: "color.hue", value: 0.72 },
      { system: "color", path: "color.saturation", value: 0.15 },
      { system: "light", path: "light.intensity", value: 0.85 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "mf-wax",
    family: "material-forms",
    name: "Wax",
    tagline: "Warm translucent softness.",
    changes: [
      { system: "material", path: "material.metalness", value: 0 },
      { system: "material", path: "material.roughness", value: 0.55 },
      { system: "material", path: "material.iridescence", value: 0.1 },
      { system: "form", path: "form.size", value: 0.72 },
      { system: "form", path: "form.smoothness", value: 0.34 },
      { system: "color", path: "color.hue", value: 0.11 },
      { system: "color", path: "color.saturation", value: 0.5 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.4 },
    ],
  },
  {
    id: "mf-bronze",
    family: "material-forms",
    name: "Bronze",
    tagline: "Ancient patinated metal.",
    changes: [
      { system: "material", path: "material.metalness", value: 0.85 },
      { system: "material", path: "material.roughness", value: 0.45 },
      { system: "material", path: "material.iridescence", value: 0.05 },
      { system: "form", path: "form.size", value: 0.6 },
      { system: "color", path: "color.hue", value: 0.09 },
      { system: "color", path: "color.saturation", value: 0.65 },
      { system: "light", path: "light.intensity", value: 1.05 },
    ],
  },
  {
    id: "mf-mercury",
    family: "material-forms",
    name: "Mercury",
    tagline: "Liquid metal beading and merging.",
    changes: [
      { system: "material", path: "material.metalness", value: 1 },
      { system: "material", path: "material.roughness", value: 0.02 },
      { system: "material", path: "material.iridescence", value: 0.3 },
      { system: "form", path: "form.size", value: 0.45 },
      { system: "form", path: "form.smoothness", value: 0.45 },
      { system: "form", path: "form.cluster", value: 5 },
      { system: "color", path: "color.hue", value: 0.62 },
      { system: "color", path: "color.saturation", value: 0.2 },
    ],
  },
  // ─── TEMPORAL PAINTINGS ─────────────────────────────────────────────────
  {
    id: "tp-watercolor",
    family: "temporal-paintings",
    name: "Watercolour",
    tagline: "Bleeding pigment on wet paper.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.brush", value: 0.9 },
      { system: "form", path: "form.strokes", value: 4 },
      { system: "form", path: "form.intensity", value: 1.8 },
      { system: "motion", path: "motion.flow", value: 0.35 },
      { system: "motion", path: "motion.chaos", value: 0.25 },
      { system: "motion", path: "motion.pulse", value: 0.35 },
      { system: "memory", path: "memory.persistence", value: 0.82 },
      { system: "memory", path: "memory.bleed", value: 0.55 },
      { system: "memory", path: "memory.feedback", value: 0.95 },
      { system: "color", path: "color.hue", value: 0.55 },
      { system: "color", path: "color.spread", value: 0.8 },
      { system: "color", path: "color.contrast", value: 1.2 },
    ],
  },
  {
    id: "tp-ink-storm",
    family: "temporal-paintings",
    name: "Ink Storm",
    tagline: "Violent black ink whipping across paper.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.brush", value: 1.2 },
      { system: "form", path: "form.strokes", value: 5 },
      { system: "form", path: "form.intensity", value: 2.1 },
      { system: "motion", path: "motion.flow", value: 1.2 },
      { system: "motion", path: "motion.chaos", value: 0.85 },
      { system: "motion", path: "motion.pulse", value: 0.4 },
      { system: "memory", path: "memory.persistence", value: 0.78 },
      { system: "memory", path: "memory.bleed", value: 0.75 },
      { system: "memory", path: "memory.feedback", value: 0.95 },
      { system: "color", path: "color.hue", value: 0.66 },
      { system: "color", path: "color.spread", value: 0.55 },
      { system: "color", path: "color.contrast", value: 1.4 },
    ],
  },
  {
    id: "tp-fresco",
    family: "temporal-paintings",
    name: "Fresco",
    tagline: "Slow chalky pigment settling on plaster.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.brush", value: 0.7 },
      { system: "form", path: "form.strokes", value: 3 },
      { system: "form", path: "form.intensity", value: 1.7 },
      { system: "motion", path: "motion.flow", value: 0.28 },
      { system: "motion", path: "motion.chaos", value: 0.15 },
      { system: "motion", path: "motion.pulse", value: 0.25 },
      { system: "memory", path: "memory.persistence", value: 0.78 },
      { system: "memory", path: "memory.bleed", value: 0.15 },
      { system: "memory", path: "memory.feedback", value: 0.9 },
      { system: "color", path: "color.hue", value: 0.08 },
      { system: "color", path: "color.spread", value: 0.7 },
      { system: "color", path: "color.contrast", value: 1.15 },
    ],
  },
  {
    id: "tp-oil",
    family: "temporal-paintings",
    name: "Oil",
    tagline: "Thick impasto smearing slowly.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.brush", value: 1.4 },
      { system: "form", path: "form.strokes", value: 4 },
      { system: "form", path: "form.intensity", value: 1.85 },
      { system: "motion", path: "motion.flow", value: 0.45 },
      { system: "motion", path: "motion.chaos", value: 0.3 },
      { system: "motion", path: "motion.pulse", value: 0.3 },
      { system: "memory", path: "memory.persistence", value: 0.8 },
      { system: "memory", path: "memory.bleed", value: 0.28 },
      { system: "memory", path: "memory.feedback", value: 0.95 },
      { system: "color", path: "color.hue", value: 0.04 },
      { system: "color", path: "color.spread", value: 0.75 },
      { system: "color", path: "color.contrast", value: 1.3 },
    ],
  },
  {
    id: "tp-neon-trail",
    family: "temporal-paintings",
    name: "Neon Trail",
    tagline: "Long luminous trails on black.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.brush", value: 0.35 },
      { system: "form", path: "form.strokes", value: 3 },
      { system: "form", path: "form.sources", value: 6 },
      { system: "form", path: "form.intensity", value: 1.9 },
      { system: "motion", path: "motion.flow", value: 0.9 },
      { system: "motion", path: "motion.chaos", value: 0.55 },
      { system: "memory", path: "memory.persistence", value: 0.96 },
      { system: "memory", path: "memory.bleed", value: 0.35 },
      { system: "memory", path: "memory.feedback", value: 1 },
      { system: "color", path: "color.hue", value: 0.83 },
      { system: "color", path: "color.spread", value: 0.65 },
      { system: "color", path: "color.contrast", value: 1.7 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "tp-dust",
    family: "temporal-paintings",
    name: "Dust",
    tagline: "Barely-there particulate drift.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.brush", value: 0.4 },
      { system: "form", path: "form.sources", value: 6 },
      { system: "form", path: "form.intensity", value: 1.9 },
      { system: "motion", path: "motion.flow", value: 0.3 },
      { system: "motion", path: "motion.chaos", value: 0.7 },
      { system: "motion", path: "motion.pulse", value: 0.35 },
      { system: "memory", path: "memory.persistence", value: 0.8 },
      { system: "memory", path: "memory.bleed", value: 0.55 },
      { system: "memory", path: "memory.feedback", value: 0.92 },
      { system: "color", path: "color.hue", value: 0.09 },
      { system: "color", path: "color.spread", value: 0.7 },
      { system: "color", path: "color.contrast", value: 1.15 },
    ],
  },
  // ─── TYPOGRAPHIC ORGANISMS ──────────────────────────────────────────────
  {
    id: "to-glyph-choir",
    family: "typographic-organisms",
    name: "Glyph Choir",
    tagline: "Marching letters in unison.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.cellSize", value: 26 },
      { system: "form", path: "form.weight", value: 0.65 },
      { system: "form", path: "form.jitter", value: 0.05 },
      { system: "motion", path: "motion.speed", value: 0.65 },
      { system: "motion", path: "motion.breath", value: 0.7 },
      { system: "motion", path: "motion.growth", value: 0.5 },
      { system: "material", path: "material.softness", value: 0.015 },
      { system: "color", path: "color.hue", value: 0.12 },
      { system: "color", path: "color.contrast", value: 1.35 },
    ],
  },
  {
    id: "to-signal-rain",
    family: "typographic-organisms",
    name: "Signal Rain",
    tagline: "Dense terminal characters cascading.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.cellSize", value: 14 },
      { system: "form", path: "form.weight", value: 0.75 },
      { system: "form", path: "form.jitter", value: 0.15 },
      { system: "motion", path: "motion.speed", value: 0.9 },
      { system: "motion", path: "motion.breath", value: 0.15 },
      { system: "motion", path: "motion.growth", value: 0.35 },
      { system: "material", path: "material.softness", value: 0.008 },
      { system: "color", path: "color.hue", value: 0.36 },
      { system: "color", path: "color.contrast", value: 1.45 },
    ],
  },
  {
    id: "to-broadside",
    family: "typographic-organisms",
    name: "Broadside",
    tagline: "Bold sliding headline ribbons.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.cellSize", value: 46 },
      { system: "form", path: "form.weight", value: 0.9 },
      { system: "form", path: "form.jitter", value: 0.05 },
      { system: "motion", path: "motion.speed", value: 0.75 },
      { system: "motion", path: "motion.breath", value: 0.3 },
      { system: "motion", path: "motion.growth", value: 0.4 },
      { system: "material", path: "material.softness", value: 0.01 },
      { system: "color", path: "color.hue", value: 0 },
      { system: "color", path: "color.contrast", value: 1.35 },
    ],
  },
  {
    id: "to-hymn",
    family: "typographic-organisms",
    name: "Hymn",
    tagline: "Soft-focus glyphs breathing gently.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.cellSize", value: 40 },
      { system: "form", path: "form.weight", value: 0.4 },
      { system: "form", path: "form.jitter", value: 0.45 },
      { system: "motion", path: "motion.speed", value: 0.5 },
      { system: "motion", path: "motion.breath", value: 0.85 },
      { system: "motion", path: "motion.growth", value: 0.6 },
      { system: "material", path: "material.softness", value: 0.12 },
      { system: "color", path: "color.hue", value: 0.78 },
      { system: "color", path: "color.contrast", value: 1.15 },
      { system: "output", path: "output.vignette", value: 0.5 },
    ],
  },
  {
    id: "to-swarm",
    family: "typographic-organisms",
    name: "Swarm",
    tagline: "Chaotic scattering of tiny characters.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.cellSize", value: 18 },
      { system: "form", path: "form.weight", value: 0.5 },
      { system: "form", path: "form.jitter", value: 0.85 },
      { system: "motion", path: "motion.speed", value: 1.2 },
      { system: "motion", path: "motion.breath", value: 0.35 },
      { system: "motion", path: "motion.growth", value: 0.5 },
      { system: "material", path: "material.softness", value: 0.03 },
      { system: "color", path: "color.hue", value: 0.55 },
      { system: "color", path: "color.contrast", value: 1.3 },
    ],
  },
  // ─── SPATIAL ILLUSIONS ──────────────────────────────────────────────────
  {
    id: "si-portal",
    family: "spatial-illusions",
    name: "Portal",
    tagline: "Deep tunnel with warped light.",
    changes: [
      { system: "form", path: "form.depth", value: 1.6 },
      { system: "form", path: "form.twist", value: 0.9 },
      { system: "motion", path: "motion.speed", value: 0.4 },
      { system: "color", path: "color.hue", value: 0.78 },
    ],
  },
  {
    id: "si-vortex",
    family: "spatial-illusions",
    name: "Vortex",
    tagline: "Fast spiralling implosion.",
    changes: [
      { system: "form", path: "form.depth", value: 2.4 },
      { system: "form", path: "form.twist", value: 1.4 },
      { system: "form", path: "form.rings", value: 18 },
      { system: "motion", path: "motion.speed", value: 1.1 },
      { system: "motion", path: "motion.warble", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.02 },
      { system: "color", path: "color.contrast", value: 1.5 },
      { system: "light", path: "light.bloom", value: 0.8 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.65 },
    ],
  },
  {
    id: "si-cathedral",
    family: "spatial-illusions",
    name: "Cathedral",
    tagline: "Slow vaulted architectural depth.",
    changes: [
      { system: "form", path: "form.depth", value: 2.8 },
      { system: "form", path: "form.twist", value: -0.4 },
      { system: "form", path: "form.rings", value: 8 },
      { system: "motion", path: "motion.speed", value: 0.1 },
      { system: "motion", path: "motion.warble", value: 0.08 },
      { system: "color", path: "color.hue", value: 0.13 },
      { system: "color", path: "color.contrast", value: 1.35 },
      { system: "light", path: "light.bloom", value: 0.9 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.8 },
      { system: "output", path: "output.vignette", value: 0.7 },
    ],
  },
  {
    id: "si-moire",
    family: "spatial-illusions",
    name: "Moiré",
    tagline: "Interference-pattern shimmer.",
    changes: [
      { system: "form", path: "form.depth", value: 0.6 },
      { system: "form", path: "form.twist", value: 0.15 },
      { system: "form", path: "form.rings", value: 24 },
      { system: "motion", path: "motion.speed", value: 0.55 },
      { system: "motion", path: "motion.warble", value: 0.8 },
      { system: "color", path: "color.hue", value: 0.5 },
      { system: "color", path: "color.contrast", value: 1.55 },
      { system: "light", path: "light.bloom", value: 0.3 },
    ],
  },
  {
    id: "si-mobius",
    family: "spatial-illusions",
    name: "Möbius",
    tagline: "Impossible ribbon folding on itself.",
    changes: [
      { system: "form", path: "form.depth", value: 1.8 },
      { system: "form", path: "form.twist", value: -1.2 },
      { system: "form", path: "form.rings", value: 14 },
      { system: "motion", path: "motion.speed", value: 0.25 },
      { system: "motion", path: "motion.warble", value: 0.35 },
      { system: "color", path: "color.hue", value: 0.88 },
      { system: "color", path: "color.contrast", value: 1.25 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.35 },
    ],
  },
  {
    id: "si-abyss",
    family: "spatial-illusions",
    name: "Abyss",
    tagline: "Bottomless dark descending well.",
    changes: [
      { system: "form", path: "form.depth", value: 2.9 },
      { system: "form", path: "form.twist", value: 0.25 },
      { system: "form", path: "form.rings", value: 6 },
      { system: "motion", path: "motion.speed", value: 0.35 },
      { system: "motion", path: "motion.warble", value: 0.15 },
      { system: "color", path: "color.hue", value: 0.6 },
      { system: "color", path: "color.contrast", value: 1.7 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.9 },
      { system: "output", path: "output.vignette", value: 0.8 },
    ],
  },
  // ─── VARIANT SHOWCASES ─────────────────────────────────────────────────
  {
    id: "lf-curl-current",
    family: "living-fields",
    name: "Curl Current",
    tagline: "Coherent streaks advected by a curl flow.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.density", value: 1.4 },
      { system: "form", path: "form.warp", value: 0.9 },
      { system: "form", path: "form.structure", value: 0.8 },
      { system: "motion", path: "motion.speed", value: 0.25 },
      { system: "motion", path: "motion.turbulence", value: 0.5 },
      { system: "color", path: "color.hue", value: 0.56 },
      { system: "color", path: "color.spread", value: 0.45 },
      { system: "light", path: "light.bloom", value: 0.6 },
    ],
  },
  {
    id: "lf-ridged-vein",
    family: "living-fields",
    name: "Ridged Veins",
    tagline: "Sharp bright ridges of matter.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.density", value: 2.4 },
      { system: "form", path: "form.warp", value: 1.2 },
      { system: "motion", path: "motion.speed", value: 0.18 },
      { system: "color", path: "color.hue", value: 0.05 },
      { system: "color", path: "color.spread", value: 0.4 },
      { system: "color", path: "color.contrast", value: 1.45 },
    ],
  },
  {
    id: "lf-cells",
    family: "living-fields",
    name: "Cell Culture",
    tagline: "Interfering reaction cells.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.density", value: 2.0 },
      { system: "motion", path: "motion.speed", value: 0.15 },
      { system: "color", path: "color.hue", value: 0.32 },
      { system: "color", path: "color.spread", value: 0.3 },
      { system: "color", path: "color.contrast", value: 1.2 },
    ],
  },
  {
    id: "mf-torus-braid",
    family: "material-forms",
    name: "Torus Braid",
    tagline: "Interlocking twisted rings.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.size", value: 0.55 },
      { system: "form", path: "form.twist", value: 0.9 },
      { system: "form", path: "form.deform", value: 0.15 },
      { system: "material", path: "material.metalness", value: 0.9 },
      { system: "material", path: "material.roughness", value: 0.2 },
      { system: "material", path: "material.iridescence", value: 0.4 },
      { system: "color", path: "color.hue", value: 0.55 },
    ],
  },
  {
    id: "mf-lattice",
    family: "material-forms",
    name: "Crystal Lattice",
    tagline: "Repeated octahedral crystals inside a cube.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.size", value: 0.5 },
      { system: "form", path: "form.twist", value: 0.3 },
      { system: "material", path: "material.metalness", value: 0.2 },
      { system: "material", path: "material.roughness", value: 0.1 },
      { system: "material", path: "material.iridescence", value: 0.7 },
      { system: "material", path: "material.clearcoat", value: 0.8 },
      { system: "color", path: "color.hue", value: 0.82 },
    ],
  },
  {
    id: "mf-dome",
    family: "material-forms",
    name: "Liquid Dome",
    tagline: "Rippling pool of molten glass.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.size", value: 0.7 },
      { system: "form", path: "form.deform", value: 0.6 },
      { system: "form", path: "form.cameraTilt", value: 0.35 },
      { system: "material", path: "material.metalness", value: 0.15 },
      { system: "material", path: "material.roughness", value: 0.08 },
      { system: "material", path: "material.translucency", value: 0.6 },
      { system: "material", path: "material.clearcoat", value: 0.9 },
      { system: "color", path: "color.hue", value: 0.58 },
      { system: "color", path: "color.saturation", value: 0.4 },
    ],
  },
  {
    id: "tp-orbits",
    family: "temporal-paintings",
    name: "Orbits",
    tagline: "Planetary trails looping across the canvas.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.sources", value: 6 },
      { system: "form", path: "form.brush", value: 0.4 },
      { system: "form", path: "form.intensity", value: 1.4 },
      { system: "motion", path: "motion.flow", value: 0.5 },
      { system: "memory", path: "memory.persistence", value: 0.95 },
      { system: "color", path: "color.hue", value: 0.6 },
      { system: "color", path: "color.spread", value: 0.7 },
    ],
  },
  {
    id: "tp-lissa",
    family: "temporal-paintings",
    name: "Lissajous",
    tagline: "Mathematical ribbons woven in time.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.sources", value: 4 },
      { system: "form", path: "form.brush", value: 0.3 },
      { system: "form", path: "form.intensity", value: 1.6 },
      { system: "motion", path: "motion.flow", value: 0.6 },
      { system: "memory", path: "memory.persistence", value: 0.97 },
      { system: "color", path: "color.hue", value: 0.83 },
      { system: "color", path: "color.spread", value: 0.6 },
      { system: "color", path: "color.contrast", value: 1.4 },
    ],
  },
  {
    id: "tp-plumes",
    family: "temporal-paintings",
    name: "Plumes",
    tagline: "Smoke rising and drifting.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.sources", value: 5 },
      { system: "form", path: "form.brush", value: 0.9 },
      { system: "form", path: "form.intensity", value: 1.1 },
      { system: "motion", path: "motion.flow", value: 0.35 },
      { system: "motion", path: "motion.chaos", value: 0.5 },
      { system: "memory", path: "memory.persistence", value: 0.9 },
      { system: "memory", path: "memory.bleed", value: 0.6 },
      { system: "color", path: "color.hue", value: 0.04 },
      { system: "color", path: "color.spread", value: 0.3 },
    ],
  },
  {
    id: "to-matrix-rain",
    family: "typographic-organisms",
    name: "Matrix Rain",
    tagline: "Cascading terminal glyphs.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.cellSize", value: 16 },
      { system: "form", path: "form.weight", value: 0.7 },
      { system: "motion", path: "motion.speed", value: 0.9 },
      { system: "motion", path: "motion.breath", value: 0.15 },
      { system: "motion", path: "motion.growth", value: 0.35 },
      { system: "material", path: "material.softness", value: 0.01 },
      { system: "color", path: "color.hue", value: 0.36 },
      { system: "color", path: "color.contrast", value: 1.4 },
    ],
  },
  {
    id: "to-marquee",
    family: "typographic-organisms",
    name: "Marquee",
    tagline: "Sliding headline ribbons.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.cellSize", value: 34 },
      { system: "form", path: "form.weight", value: 0.8 },
      { system: "form", path: "form.melt", value: 0.2 },
      { system: "motion", path: "motion.speed", value: 0.6 },
      { system: "motion", path: "motion.breath", value: 0.25 },
      { system: "motion", path: "motion.growth", value: 0.35 },
      { system: "color", path: "color.hue", value: 0.02 },
      { system: "color", path: "color.contrast", value: 1.3 },
    ],
  },
  {
    id: "to-cloud",
    family: "typographic-organisms",
    name: "Word Cloud",
    tagline: "Floating scattered glyphs drifting in space.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.weight", value: 0.55 },
      { system: "form", path: "form.jitter", value: 0.6 },
      { system: "form", path: "form.dissolve", value: 0.2 },
      { system: "motion", path: "motion.speed", value: 0.55 },
      { system: "motion", path: "motion.breath", value: 0.55 },
      { system: "motion", path: "motion.growth", value: 0.55 },
      { system: "material", path: "material.softness", value: 0.03 },
      { system: "color", path: "color.hue", value: 0.65 },
    ],
  },
  {
    id: "to-dissolve",
    family: "typographic-organisms",
    name: "Dissolution",
    tagline: "Letterforms crumbling into dust.",
    changes: [
      { system: "form", path: "form.variant", value: 0 },
      { system: "form", path: "form.cellSize", value: 42 },
      { system: "form", path: "form.weight", value: 0.7 },
      { system: "form", path: "form.dissolve", value: 0.55 },
      { system: "form", path: "form.melt", value: 0.35 },
      { system: "form", path: "form.fracture", value: 0.4 },
      { system: "motion", path: "motion.speed", value: 0.45 },
      { system: "motion", path: "motion.breath", value: 0.4 },
      { system: "motion", path: "motion.growth", value: 0.55 },
      { system: "material", path: "material.softness", value: 0.04 },
      { system: "color", path: "color.hue", value: 0.08 },
    ],
  },
  {
    id: "si-hallway",
    family: "spatial-illusions",
    name: "Hall of Columns",
    tagline: "Endless colonnade sliding past.",
    changes: [
      { system: "form", path: "form.variant", value: 1 },
      { system: "form", path: "form.repeat", value: 1.4 },
      { system: "form", path: "form.cameraSway", value: 0.5 },
      { system: "motion", path: "motion.speed", value: 0.6 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.08 },
      { system: "light", path: "light.bloom", value: 0.7 },
    ],
  },
  {
    id: "si-menger",
    family: "spatial-illusions",
    name: "Menger Descent",
    tagline: "Falling through a self-similar fractal.",
    changes: [
      { system: "form", path: "form.variant", value: 2 },
      { system: "form", path: "form.repeat", value: 2.0 },
      { system: "form", path: "form.cameraSway", value: 0.2 },
      { system: "motion", path: "motion.speed", value: 0.35 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.4 },
      { system: "color", path: "color.hue", value: 0.55 },
      { system: "color", path: "color.contrast", value: 1.3 },
      { system: "light", path: "light.bloom", value: 0.5 },
    ],
  },
  {
    id: "si-vault",
    family: "spatial-illusions",
    name: "Vaulted Nave",
    tagline: "Sacred architecture in slow drift.",
    changes: [
      { system: "form", path: "form.variant", value: 3 },
      { system: "form", path: "form.repeat", value: 1.8 },
      { system: "form", path: "form.cameraSway", value: 0.3 },
      { system: "motion", path: "motion.speed", value: 0.2 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.7 },
      { system: "color", path: "color.hue", value: 0.1 },
      { system: "color", path: "color.contrast", value: 1.4 },
      { system: "light", path: "light.bloom", value: 0.9 },
      { system: "output", path: "output.vignette", value: 0.6 },
    ],
  },
  // ─── SPATIAL ILLUSIONS · KALEIDOSCOPE ─────────────────────────────────
  {
    id: "si-kaleido-petal",
    family: "spatial-illusions",
    name: "Petal Kaleidoscope",
    tagline: "Six-fold mirror garden of concentric petals.",
    changes: [
      { system: "form", path: "form.variant", value: 4 },
      { system: "form", path: "form.mirrors", value: 6 },
      { system: "form", path: "form.symmetry", value: 0.95 },
      { system: "form", path: "form.ripple", value: 0.5 },
      { system: "form", path: "form.rotation", value: 0.3 },
      { system: "form", path: "form.kernel", value: 1 },
      { system: "form", path: "form.rings", value: 10 },
      { system: "color", path: "color.hue", value: 0.82 },
      { system: "color", path: "color.contrast", value: 1.4 },
      { system: "light", path: "light.bloom", value: 0.7 },
      { system: "output", path: "output.vignette", value: 0.35 },
    ],
  },
  {
    id: "si-kaleido-crystal",
    family: "spatial-illusions",
    name: "Crystal Wheel",
    tagline: "Twelve-fold shattered stained-glass rotor.",
    changes: [
      { system: "form", path: "form.variant", value: 4 },
      { system: "form", path: "form.mirrors", value: 12 },
      { system: "form", path: "form.symmetry", value: 1.0 },
      { system: "form", path: "form.ripple", value: 0.15 },
      { system: "form", path: "form.rotation", value: -0.6 },
      { system: "form", path: "form.kernel", value: 2 },
      { system: "form", path: "form.rings", value: 14 },
      { system: "color", path: "color.hue", value: 0.56 },
      { system: "color", path: "color.contrast", value: 1.55 },
      { system: "light", path: "light.bloom", value: 0.55 },
    ],
  },
  {
    id: "si-kaleido-galaxy",
    family: "spatial-illusions",
    name: "Mandala Galaxy",
    tagline: "Eight-fold swirling nebular mandala.",
    changes: [
      { system: "form", path: "form.variant", value: 4 },
      { system: "form", path: "form.mirrors", value: 8 },
      { system: "form", path: "form.symmetry", value: 0.7 },
      { system: "form", path: "form.ripple", value: 0.9 },
      { system: "form", path: "form.rotation", value: 0.15 },
      { system: "form", path: "form.kernel", value: 3 },
      { system: "form", path: "form.twist", value: 0.9 },
      { system: "color", path: "color.hue", value: 0.05 },
      { system: "color", path: "color.contrast", value: 1.3 },
      { system: "light", path: "light.bloom", value: 0.85 },
      { system: "output", path: "output.vignette", value: 0.55 },
    ],
  },
  {
    id: "si-kaleido-stripes",
    family: "spatial-illusions",
    name: "Ribbon Rosette",
    tagline: "Four mirrors of hard geometric stripes.",
    changes: [
      { system: "form", path: "form.variant", value: 4 },
      { system: "form", path: "form.mirrors", value: 4 },
      { system: "form", path: "form.symmetry", value: 1.0 },
      { system: "form", path: "form.ripple", value: 0.05 },
      { system: "form", path: "form.rotation", value: 0.8 },
      { system: "form", path: "form.kernel", value: 0 },
      { system: "form", path: "form.rings", value: 6 },
      { system: "color", path: "color.hue", value: 0.14 },
      { system: "color", path: "color.contrast", value: 1.7 },
      { system: "light", path: "light.bloom", value: 0.3 },
    ],
  },
  // ─── SPATIAL ILLUSIONS · HYPERCUBE ────────────────────────────────────
  {
    id: "si-hypercube",
    family: "spatial-illusions",
    name: "Tesseract Grid",
    tagline: "A rotating lattice of nested 4D cubes.",
    changes: [
      { system: "form", path: "form.variant", value: 5 },
      { system: "form", path: "form.cells", value: 4 },
      { system: "form", path: "form.projection", value: 0.9 },
      { system: "form", path: "form.repeat", value: 1.4 },
      { system: "form", path: "form.twist", value: 0.6 },
      { system: "motion", path: "motion.speed", value: 0.25 },
      { system: "atmosphere", path: "atmosphere.fog", value: 0.55 },
      { system: "color", path: "color.hue", value: 0.62 },
      { system: "color", path: "color.contrast", value: 1.4 },
      { system: "light", path: "light.bloom", value: 0.75 },
    ],
  },
];

export function recipesForFamily(family: string): Recipe[] {
  return RECIPES.filter((r) => r.family === family);
}
